[package]
name = "pra"
version = "0.1.0"
authors = ["Sebastian Angel <sebastian.angel@cis.upenn.edu>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
rand_distr = "0.2.2"
statistical = "1.0.0"

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "pra"
harness = false
